# Generated by Django 6.0.4 on 2026-04-11 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fauna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_spotted', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='fauna.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
