# Generated by Django 6.0.4 on 2026-04-15 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['user', 'date_spotted'], name='obs_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['species', 'date_spotted'], name='obs_species_date_idx'),
        ),
    ]
