# Generated by Django 6.0.4 on 2026-05-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
