# Generated by Django 6.0.4 on 2026-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('scientific_name', models.CharField(max_length=160, unique=True)),
                ('conservation_status', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], db_index=True, default='LC', max_length=2)),
                ('summary', models.TextField(blank=True)),
                ('is_native_to_nt', models.BooleanField(db_index=True, default=False)),
                ('habitats', models.ManyToManyField(blank=True, related_name='species', to='fauna.habitat')),
            ],
            options={
                'ordering': ('name', 'scientific_name'),
                'indexes': [models.Index(fields=['is_native_to_nt', 'conservation_status'], name='species_nt_status_idx')],
            },
        ),
    ]
