# Generated by Django 6.0.4 on 2026-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('ranger', 'Ranger'), ('researcher', 'Researcher')], default='viewer', max_length=20),
        ),
    ]
